name: appkinson
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
platform: ios, '10.0'

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 
  dropdownfield: ^1.0.3
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  table_calendar: ^3.0.6
  google_fonts:
  font_awesome_flutter: ^10.1.0
  flutter_downloader: ^1.5.2
  #permission_handler: ^5.0.1
  network_to_file_image: ^4.0.1
  sqflite: ^2.0.3+1
  rxdart: ^0.27.5
  path_provider: 
  http: ^0.13.5
  provider: ^6.0.3
  flutter_local_notifications: ^9.8.0+1
  workmanager: ^0.5.0
  
  line_awesome_flutter: ^2.0.0
  flutter_screenutil: ^5.5.3+2
  #animated_theme_switcher: ^1.0.6
  foldable_sidebar: ^1.0.0
  image_picker: ^0.8.5+3
  #image_cropper: ^1.2.0
  swipedetector: ^1.2.0
  video_player: ^2.4.7
  syncfusion_flutter_calendar: ^20.2.45
  syncfusion_flutter_charts: ^20.2.45
  decimal: ^2.2.0
  #pedometer: ^0.0.5
  percent_indicator: ^4.2.2
  flutter_launcher_icons: 
  shared_preferences: 
  # nova_alarm_plugin: ^0.1.0
  email_validator: ^2.1.17
  url_launcher: ^6.1.5
  

  date_range_picker: ^1.0.5
  charts_flutter: ^0.12.0

  timezone: ^0.8.0
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.



  flutter_localizations:
    sdk: flutter

  intl: 
  #intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  image_path: "assets/images/cerebroMovimiento.png"
  android: true
  ios: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/cerebroAzul.png
     - assets/images/usuario.png
     - assets/icons/
     - assets/images/coronadr.png
     - assets/images/starsBackGround.png
     - assets/images/abrir-caja.png
     - assets/images/advertir.png
     - assets/images/condiciones.png
     - assets/images/calendario.png
     - assets/images/formulario.png
     - assets/images/obrero.png
     - assets/images/tristeFeliz.png
     - assets/images/pacientes.png
     - assets/images/ingenieria.png
     - assets/images/toolsBack.png
     - assets/images/usuario(1).png
     - assets/images/user.png
     - assets/images/cerebroMovimiento.png
     - assets/images/relationRequest.png
     - assets/images/burned.png
     - assets/images/distance.png
     - assets/images/step.png
     - assets/images/ejercicio.png
     - assets/images/food.png
     - assets/images/heart.png
     - assets/images/logostep.png
     - assets/images/news.png
     - assets/images/parkinson.png
     - assets/images/parkinsonHand.png
     - assets/images/medicines.png
     - assets/images/reporter.png
     - assets/images/game.png
     - assets/images/cerrar-sesion.png
     - assets/images/pedometer.png
     - assets/images/puzzle.png
     - assets/images/perfil2.png
     - assets/images/pie-chart.png
     - assets/images/bar-graph.png
     - assets/images/output-onlinepngtools (1).png
     - assets/images/output-onlinepngtools (2).png
     - assets/images/representation.png
     - assets/images/output-onlinepngtools (3).png
     - assets/images/1-CALENDARIO.png
     - assets/images/2-MEDICINAS.png
     - assets/images/3-RECORDATORIO.png
     - assets/images/4-PERFIL.png
     - assets/images/5-TOOLBOX-PROACTIVIDAD.png
     - assets/images/6-SENTIMIENTOS.png
     - assets/images/7-ALERTA.png
     - assets/images/8-COMIDA.png
     - assets/images/9-PODOMETRO.png
     - assets/images/10-NOTICIAS.png
     - assets/images/11-GAMES-JUEGOS.png
     - assets/images/12-EJERCICIOS.png
     - assets/images/13- AÑADIR.png
     - assets/images/14-LISTA.png
     - assets/images/15-PACIENTES.png
     - assets/images/line-chart.png
     - assets/images/desplazarse.png
     





  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-ExtraLight.ttf
    - family: Raleway2
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf
    - family: RalewayBold
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
